# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package Publish

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: maven-settings-action
      uses: s4u/maven-settings-action@v3.0.0

    - name: Build with Maven
      run: mvn -B clean install --file pom.xml

    - name: Set up Maven Central Repository
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: central
        server-username: OSSRH_USERNAME
        server-password: OSSRH_TOKEN

    - name: Publish package to Maven Central
      run: mvn deploy
      env:
        SIGN_KEY_ID: ${{ secrets.SIGN_KEY_ID }}
        SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
        SIGN_KEY: ${{ secrets.SIGN_KEY }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}